### ISSUE TITLE
Cannot update server via init.js

### ISSUE THREAD

**Issue by bdickason** [srstafford1996/chicken-server#12]
When running `node server/database/init.js`, I get an error running the init script.

I've tried dropping and re-creating the database which also doesn't fix the issue.
````
Structuring database.
{ Error: ER_BAD_TABLE_ERROR: Unknown table 'tekkenchicken.attacks_tc'
    at Query.Sequence._packetToError (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/Connection.js:208:25)
    at pool.getConnection (/Users/bdickason/code/chicken-server/server/database/init.js:128:16)
    at Handshake.onConnect (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/Pool.js:64:7)
    at Handshake.Sequence.end (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Handshake.Sequence.OkPacket (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:95:8)
    at Protocol._parsePacket (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/Connection.js:103:28)
  code: 'ER_BAD_TABLE_ERROR',
  errno: 1051,
  sqlState: '42S02',
  index: 0 }
/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

Error: Connection already released
    at Pool.releaseConnection (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/Pool.js:138:13)
    at PoolConnection.release (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/PoolConnection.js:35:15)
    at Query.connection.query [as _callback] (/Users/bdickason/code/chicken-server/server/database/init.js:136:24)
    at Query.Sequence.end (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query.ErrorPacket (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
    at Protocol._parsePacket (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/bdickason/code/chicken-server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
````

**Comment by bdickason** [comment]
Solved by a936cc838fe960acca57b2c5bacb2b2012db2407
