### ISSUE TITLE
Tests: 'after each' hook sometimes reports null value for connection

### ISSUE THREAD

**Issue by bdickason** [srstafford1996/chicken-server#14]
4 passing (63ms)
  1 failing

  1) Framedata API Controller "after each" hook: Delete test frame data:
     Uncaught TypeError: Cannot read property 'query' of null
      at pool.getConnection (test/test.js:181:31)
      at Ping.onOperationComplete [as _callback] (node_modules/mysql/lib/Pool.js:110:5)
      at Ping.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
      at Ping.Sequence.OkPacket (node_modules/mysql/lib/protocol/sequences/Sequence.js:95:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:75:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at TCP.onread (net.js:547:20)

**Comment by bdickason** [comment]
Resolved by #5
